FROM zhrkasm.azurecr.io/base:latest

# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel

# Copy installation files
COPY ./install $TMP_SCRIPTS/

# Install Microsoft Edge
RUN bash $TMP_SCRIPTS/edge/install.sh

