name: Build KASM images

on:
  schedule:
    - cron: '0 1 * * 0'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  vault-test:
    name: vault test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.zhr.one
          role: kasm-images
          path: github
          method: jwt
          jwtGithubAudience: sigstore
          secrets: |
            ci-cd/kasm-images/acr ACR_ENDPOINT | ACR_ENDPOINT ;
            ci-cd/kasm-images/acr ACR_PASSWORD | ACR_PASSWORD ;
            ci-cd/kasm-images/acr ACR_USERNAME | ACR_USERNAME ;
            ci-cd/kasm-images/ssh SSH_PRIV_KEY | SSH_PRIV_KEY ;
            ci-cd/kasm-images/ssh SSH_PUB_KEY | SSH_PUB_KEY

  build-base:
    name: base image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    with:
      image: base
      dockerfile: Dockerfile.base
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}
      sshPriv: ${{ secrets.SSH_PRIV_KEY }} 
      sshPub: ${{ secrets.SSH_PUB_KEY }}

  build-base-app:
    name: base-app image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base
    with:
      image: base-app
      dockerfile: Dockerfile.base-app
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}

  build-desktop:
    name: desktop image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base
    with:
      image: desktop
      dockerfile: Dockerfile.desktop
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}

  build-terminal:
    name: terminal image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base-app
    with:
      image: apps/terminal
      dockerfile: Dockerfile.terminal
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}

  build-vscode:
    name: vscode image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base-app
    with:
      image: apps/vscode
      dockerfile: Dockerfile.vscode
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}