name: Build KASM images

on:
  schedule:
    - cron: '0 1 * * 0'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-base:
    name: Build base image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    with:
      image: kasm/base
      dockerfile: Dockerfile.base
    secrets:
      password: ${{ secrets.ARTIFACT_PW }}
      sshPriv: ${{ secrets.SSH_PRIV_KEY }} 
      sshPub: ${{ secrets.SSH_PUB_KEY }}

  build-base-app:
    name: Build base-app image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base
    with:
      image: kasm/base-app
      dockerfile: Dockerfile.base-app
    secrets:
      password: ${{ secrets.ARTIFACT_PW }}

  build-desktop:
    name: Build desktop image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base
    with:
      image: kasm/desktop
      dockerfile: Dockerfile.desktop
    secrets:
      password: ${{ secrets.ARTIFACT_PW }}
      
  build-vscode:
    name: Build vscode image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base-app
    with:
      image: kasm/vscode
      dockerfile: Dockerfile.vscode
    secrets:
      password: ${{ secrets.ARTIFACT_PW }}
