name: Build KASM images

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  KASM_VERSION: 1.16.1

jobs:
  build-base:
    name: base image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    with:
      base_image: core-ubuntu-noble
      base_tag: ${{ env.KASM_VERSION }}
      image: base
      dockerfile: Dockerfile.base
    secrets:
      registry: ${{ secrets.DOCKER_ENDPOINT }}
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      sshPriv: ${{ secrets.SSH_PRIV_KEY }} 
      sshPub: ${{ secrets.SSH_PUB_KEY }}

  build-base-apps:
    name: base-apps image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base
    with:
      base_image: base-ubuntu
      base_tag: ${{ env.KASM_VERSION }}
      image: base-apps
      dockerfile: Dockerfile.base-apps
    secrets:
      registry: ${{ secrets.DOCKER_ENDPOINT }}
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  build-desktop:
    name: desktop image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base
    with:
      base_image: base-ubuntu
      base_tag: ${{ env.KASM_VERSION }}
      image: desktop
      dockerfile: Dockerfile.desktop
    secrets:
      registry: ${{ secrets.DOCKER_ENDPOINT }}
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  build-terminal:
    name: terminal image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base-apps
    with:
      base_image: base-apps
      base_tag: ${{ env.KASM_VERSION }}
      image: apps/terminal
      dockerfile: Dockerfile.terminal
    secrets:
      registry: ${{ secrets.DOCKER_ENDPOINT }}
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  build-vscode:
    name: vscode image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base-apps
    with:
      base_image: base-apps
      base_tag: ${{ env.KASM_VERSION }}
      image: apps/vscode
      dockerfile: Dockerfile.vscode
    secrets:
      registry: ${{ secrets.DOCKER_ENDPOINT }}
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
