name: Build KASM images

on:
  schedule:
    - cron: '0 1 * * 0'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
   REGISTRY: docker.zhr.one
   USERNAME: github

jobs:
  build-base:
    name: Build base image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    with:
      registry: ${{ env.REGISTRY }}
      username: ${{ env.USERNAME }}
      image: kasm/base
      dockerfile: Dockerfile.base
    secrets:
      password: ${{ secrets.ARTIFACT_PW }}

  build-desktop:
    name: Build desktop image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base
    with:
      registry: ${{ env.REGISTRY }}
      username: ${{ env.USERNAME }}
      image: kasm/desktop
      dockerfile: Dockerfile.desktop
    secrets:
      password: ${{ secrets.ARTIFACT_PW }}