name: Build KASM images

on:
  schedule:
    - cron: '0 1 * * 0'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-base:
    name: base image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    with:
      image: kasm/base
      dockerfile: Dockerfile.base
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}
      sshPriv: ${{ secrets.SSH_PRIV_KEY }} 
      sshPub: ${{ secrets.SSH_PUB_KEY }}

  build-base-app:
    name: base-app image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base
    with:
      image: kasm/base-app
      dockerfile: Dockerfile.base-app
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}

  build-desktop:
    name: desktop image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base
    with:
      image: kasm/desktop
      dockerfile: Dockerfile.desktop
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}

  build-terminal:
    name: terminal image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base-app
    with:
      image: kasm/terminal
      dockerfile: Dockerfile.terminal
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}

  build-vscode:
    name: vscode image
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    needs: build-base-app
    with:
      image: kasm/vscode
      dockerfile: Dockerfile.vscode
    secrets:
      registry: ${{ secrets.ACR_ENDPOINT }}
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}