name: Build personal-desktop

on:
  schedule:
    - cron: '0 1 * * 0'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: vladzaharia/kasm-images/.github/workflows/tmpl-docker-build-push.yml@main
    with:
      registry: docker.zhr.one
      image: personal-desktop
    secrets:
      username: ${{ secrets.ARTIFACT_USER }}
      password: ${{ secrets.ARTIFACT_PW }}
