name: Docker Build and Push

on:
  workflow_call:
    inputs:
      registry:
        description: Registry to use for authentication and pushing
        required: false
        default: docker.zhr.one
        type: string
      username:
        description: Username of user for registry authentication
        required: false
        default: github
        type: string
      image:
        description: Name of image to build and push
        required: true
        type: string
      dockerfile:
        description: Dockerfile to build and push
        required: true
        type: string
      platforms:
        description: Platforms to build images for
        required: false
        default: linux/arm64,linux/amd64
        type: string
    secrets:
      password:
        description: Password of user for registry authentication
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ inputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.registry }}/${{ inputs.image }}
          tags: |
            type=schedule,pattern=weekly
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{ is_default_branch }}
            type=raw,value=testing,enable=${{ github.event_name == 'pull_request' }}

      - name: Build ${{ inputs.image }} image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
